"""create scene_plans and visual_assets tables

Revision ID: 40f93bf44fe1
Revises: fe76b5648563
Create Date: 2026-06-03 12:19:51.771707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f93bf44fe1'
down_revision: Union[str, Sequence[str], None] = 'fe76b5648563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('scene_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('narration_text', sa.Text(), nullable=False),
    sa.Column('estimated_duration', sa.Float(), nullable=False),
    sa.Column('visual_type', sa.String(length=50), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_plans_id'), 'scene_plans', ['id'], unique=False)
    op.create_index(op.f('ix_scene_plans_script_id'), 'scene_plans', ['script_id'], unique=False)
    op.create_table('visual_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('search_keywords', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scene_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visual_assets_id'), 'visual_assets', ['id'], unique=False)
    op.create_index(op.f('ix_visual_assets_scene_id'), 'visual_assets', ['scene_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visual_assets_scene_id'), table_name='visual_assets')
    op.drop_index(op.f('ix_visual_assets_id'), table_name='visual_assets')
    op.drop_table('visual_assets')
    op.drop_index(op.f('ix_scene_plans_script_id'), table_name='scene_plans')
    op.drop_index(op.f('ix_scene_plans_id'), table_name='scene_plans')
    op.drop_table('scene_plans')
    # ### end Alembic commands ###
