"""add keywords and seo metadata

Revision ID: 4189fdbcb023
Revises: e830cd17c54b
Create Date: 2026-06-03 11:58:18.246369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4189fdbcb023'
down_revision: Union[str, Sequence[str], None] = 'e830cd17c54b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seo_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('hashtags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seo_metadata_id'), 'seo_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_seo_metadata_script_id'), 'seo_metadata', ['script_id'], unique=False)
    op.add_column('topics', sa.Column('keywords', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'keywords')
    op.drop_index(op.f('ix_seo_metadata_script_id'), table_name='seo_metadata')
    op.drop_index(op.f('ix_seo_metadata_id'), table_name='seo_metadata')
    op.drop_table('seo_metadata')
    # ### end Alembic commands ###
