"""create subtitle_assets and video_assets tables

Revision ID: 424f5f8f6519
Revises: 40f93bf44fe1
Create Date: 2026-06-03 12:27:19.241432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '424f5f8f6519'
down_revision: Union[str, Sequence[str], None] = '40f93bf44fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtitle_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('subtitle_path', sa.String(length=512), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtitle_assets_id'), 'subtitle_assets', ['id'], unique=False)
    op.create_index(op.f('ix_subtitle_assets_script_id'), 'subtitle_assets', ['script_id'], unique=True)
    op.create_table('video_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('audio_id', sa.Integer(), nullable=False),
    sa.Column('video_path', sa.String(length=512), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('resolution', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_id'], ['audio_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_assets_audio_id'), 'video_assets', ['audio_id'], unique=False)
    op.create_index(op.f('ix_video_assets_id'), 'video_assets', ['id'], unique=False)
    op.create_index(op.f('ix_video_assets_script_id'), 'video_assets', ['script_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_assets_script_id'), table_name='video_assets')
    op.drop_index(op.f('ix_video_assets_id'), table_name='video_assets')
    op.drop_index(op.f('ix_video_assets_audio_id'), table_name='video_assets')
    op.drop_table('video_assets')
    op.drop_index(op.f('ix_subtitle_assets_script_id'), table_name='subtitle_assets')
    op.drop_index(op.f('ix_subtitle_assets_id'), table_name='subtitle_assets')
    op.drop_table('subtitle_assets')
    # ### end Alembic commands ###
