"""add asset_downloads table

Revision ID: abb918847d49
Revises: 82cfee36eb6c
Create Date: 2026-06-04 14:43:55.651160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abb918847d49'
down_revision: Union[str, Sequence[str], None] = '82cfee36eb6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_downloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('visual_asset_id', sa.Integer(), nullable=True),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('search_query', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('local_path', sa.String(length=512), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scene_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visual_asset_id'], ['visual_assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_downloads_id'), 'asset_downloads', ['id'], unique=False)
    op.create_index(op.f('ix_asset_downloads_scene_id'), 'asset_downloads', ['scene_id'], unique=False)
    op.create_index(op.f('ix_asset_downloads_visual_asset_id'), 'asset_downloads', ['visual_asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_downloads_visual_asset_id'), table_name='asset_downloads')
    op.drop_index(op.f('ix_asset_downloads_scene_id'), table_name='asset_downloads')
    op.drop_index(op.f('ix_asset_downloads_id'), table_name='asset_downloads')
    op.drop_table('asset_downloads')
    # ### end Alembic commands ###
