"""create audio_assets table

Revision ID: fe76b5648563
Revises: 4189fdbcb023
Create Date: 2026-06-03 12:10:38.138560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe76b5648563'
down_revision: Union[str, Sequence[str], None] = '4189fdbcb023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('audio_path', sa.String(length=512), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('voice_model', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_assets_id'), 'audio_assets', ['id'], unique=False)
    op.create_index(op.f('ix_audio_assets_script_id'), 'audio_assets', ['script_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_assets_script_id'), table_name='audio_assets')
    op.drop_index(op.f('ix_audio_assets_id'), table_name='audio_assets')
    op.drop_table('audio_assets')
    # ### end Alembic commands ###
