import logging
import time
from typing import Optional
from sqlalchemy.orm import Session
from database.postgres import SessionLocal
from database.models import Topic, Script, SEOMetadata
from agents.research_agent import ResearchAgent
from agents.script_agent import ScriptAgent
from agents.seo_agent import SEOAgent

logger = logging.getLogger("content_pipeline")

def run_content_pipeline(niche: str, db: Optional[Session] = None) -> dict:
    """
    Orchestrates the entire Phase 1 content generation workflow:
    Research Agent (Topics) -> Script Agent (Script) -> SEO Agent (SEO Metadata).
    Persists all stages to the database and returns a structure of their record IDs.
    """
    logger.info("Starting content pipeline")
    
    opened_session = False
    if db is None:
        db = SessionLocal()
        opened_session = True
        
    try:
        # Initialize agents
        research_agent = ResearchAgent()
        script_agent = ScriptAgent()
        seo_agent = SEOAgent()
        
        # 1. Research Agent -> Generate and save topics
        logger.info("[TIMING] ContentPipeline: Before research phase")
        start_research = time.time()
        logger.info("Generating topics")
        candidates = research_agent.generate_topics(niche=niche, db=db)
        logger.info(f"[TIMING] ContentPipeline: After research phase (Duration: {time.time() - start_research:.4f}s)")
        
        if not candidates:
            logger.error("No valid topics were generated by Research Agent.")
            raise ValueError("No valid topics generated.")
            
        logger.info("Topics saved")
        
        # 2. Select top candidate based on score
        candidate_topics = [c.topic for c in candidates]
        db_topic = db.query(Topic).filter(
            Topic.topic.in_(candidate_topics),
            Topic.status == "pending"
        ).order_by(Topic.score.desc()).first()
        
        if not db_topic:
            # Fallback to any pending topic in the database
            db_topic = db.query(Topic).filter(Topic.status == "pending").order_by(Topic.score.desc()).first()
            
        if not db_topic:
            logger.error("No pending topic record found in the database.")
            raise ValueError("No pending topic found in database.")
            
        topic_id = db_topic.id
        logger.info(f"Selected top topic: '{db_topic.topic}' (ID: {topic_id}) with score {db_topic.score}")
        
        # 3. Script Agent -> Generate and save script
        logger.info("[TIMING] ContentPipeline: Before script phase")
        start_script = time.time()
        logger.info("Generating script")
        script_doc = script_agent.generate_script(topic_id=topic_id, db=db)
        logger.info(f"[TIMING] ContentPipeline: After script phase (Duration: {time.time() - start_script:.4f}s)")
        
        script_record = db.query(Script).filter(Script.topic_id == topic_id).first()
        if not script_record:
            logger.error("Failed to retrieve saved script record.")
            raise ValueError("Saved script record not found in database.")
            
        script_id = script_record.id
        logger.info("Script saved")
        
        # 4. SEO Agent -> Generate and save SEO metadata
        logger.info("Generating SEO metadata")
        seo_doc = seo_agent.generate_metadata(script_id=script_id, db=db)
        
        seo_record = db.query(SEOMetadata).filter(SEOMetadata.script_id == script_id).first()
        if not seo_record:
            logger.error("Failed to retrieve saved SEO metadata record.")
            raise ValueError("Saved SEO metadata record not found in database.")
            
        seo_id = seo_record.id
        logger.info("Metadata saved")
        
        # 5. Build return structure
        result = {
            "topic_id": topic_id,
            "script_id": script_id,
            "seo_id": seo_id
        }
        logger.info(f"Content pipeline executed successfully: {result}")
        return result
        
    except Exception as e:
        logger.error(f"Content pipeline execution failed: {e}")
        raise e
    finally:
        if opened_session:
            db.close()
